library(readr)
library(lubridate)
sim <- read_csv("obitos/ministerio/sim_2006_16.csv")
sim$DTOBITO <- as.Date(sim$DTOBITO, format = "%d%m%Y")
sim$DTNASC <- as.Date(sim$DTNASC, format = "%d%m%Y")
sim$IDADE <- round((sim$DTOBITO - sim$DTNASC)/365)
sim <- subset(sim, sim$CODMUNRES == 420540)
sim <- sim[,c(8:13,40)]
sim$IDADE <- as.numeric(sim$IDADE)
sim$SEXO <- as.factor(sim$SEXO)
sim$RACACOR <- as.factor(sim$RACACOR)
sim$ESTCIV <- as.factor(sim$ESTCIV)
sim$ESC <- as.factor(sim$ESC)
sim$OCUP <- as.factor(sim$OCUP)
sim$CAUSABAS <- as.factor(sim$CAUSABAS)